// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestConnectDB;

#nullable disable

namespace TestConnectDB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241026023305_staj261024")]
    partial class staj261024
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TestConnectDB.CommentLite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentsWork")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SotrudnikIdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SotrudnikIdId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("TestConnectDB.ReportLite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateReport")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nomerreport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StajIdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StajIdId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("TestConnectDB.SotrudnikLite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Dater")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fio")
                        .HasColumnType("TEXT");

                    b.Property<string>("FioBeforeMarry")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Marry")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Pol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sotrudnik");
                });

            modelBuilder.Entity("TestConnectDB.StajLite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BeginWorkSotrudnik")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndWorkSotrudnik")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GosWorkSotrudnik")
                        .HasColumnType("TEXT");

                    b.Property<int>("SotrudnikIdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SotrudnikIdId");

                    b.ToTable("Staj");
                });

            modelBuilder.Entity("TestConnectDB.CommentLite", b =>
                {
                    b.HasOne("TestConnectDB.SotrudnikLite", "SotrudnikId")
                        .WithMany()
                        .HasForeignKey("SotrudnikIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SotrudnikId");
                });

            modelBuilder.Entity("TestConnectDB.ReportLite", b =>
                {
                    b.HasOne("TestConnectDB.StajLite", "StajId")
                        .WithMany()
                        .HasForeignKey("StajIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StajId");
                });

            modelBuilder.Entity("TestConnectDB.StajLite", b =>
                {
                    b.HasOne("TestConnectDB.SotrudnikLite", "SotrudnikId")
                        .WithMany()
                        .HasForeignKey("SotrudnikIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SotrudnikId");
                });
#pragma warning restore 612, 618
        }
    }
}
